#!/bin/bash
# elk stack server setup script
# first run git clone https://github.com/jstelwag/iot-monitor
# then sh iot-monitor/src/main/bash/elk-server-setup

sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install oracle-java8-installer
#sudo apt-get -y install collectd

cat <<EOF >interfaces
# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto enp0s3
iface enp0s3 inet static
 address 192.168.178.101
 netmask 255.255.255.0
 gateway 192.168.178.1
 dns-nameservers 8.8.8.8
EOF
sudo mv interfaces /etc/network

# Elastic
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
sudo apt-get -y install apt-transport-https
echo "deb https://artifacts.elastic.co/packages/5.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-5.x.list
sudo apt-get update
sudo apt-get -y install elasticsearch
sudo /bin/systemctl daemon-reload
sudo /bin/systemctl enable elasticsearch.service

echo "cluster.name: kasteel-nijswiller" | sudo tee -a /etc/elasticsearch/elasticsearch.yml
echo "node.name: nijswiller-1" | sudo tee -a /etc/elasticsearch/elasticsearch.yml
echo "node.rack: kasteel-brix" | sudo tee -a /etc/elasticsearch/elasticsearch.yml

# Logstash
sudo apt-get -y install logstash
sudo /bin/systemctl daemon-reload
sudo /bin/systemctl enable logstash.service

cat <<EOF > udp-9000.conf
input {
  udp { port => 9000 }
}
filter {
  grok {
    match => { "message" => "(?<application>.*?):( (?<log-level>(DEBUG|INFO|WARN|ERROR)):)? (?<message>.*)"}
    overwrite => ["message"]
  }

  if [application] =~ "knx-event" {
    grok {
      match => { "message" => "receiver: (?<location>.*?) \((?<device-type>.*?)\) (?<device>.*?), (?<from-address>.*?)->(?<to-address>.*?) L_Data.ind, (?<l-data>.*?), tpdu (?<tpdu>.*?)" }
    }
  }
}
output {
  if [application] =~ "knx-event" {
    elasticsearch {
      hosts => "localhost:9200"
      index => "knx-%{+YYYY.MM.dd}"
    }
  } else {
    elasticsearch {
      hosts => "localhost:9200"
    }
  }
}
EOF
sudo mv udp-9000.conf /etc/logstash/conf.d/

#Kibana
sudo apt-get -y install kibana
sudo /bin/systemctl daemon-reload
sudo /bin/systemctl enable kibana.service
echo 'server.host: "0.0.0.0"' | sudo tee -a /etc/kibana/kibana.yml

exit 0