#!/bin/bash
# elk stack server setup script
# first run git clone https://github.com/jstelwag/iot-monitor
# then sh iot-monitor/src/main/bash/elk-server-setup

sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install openjdk-8-jdk curl apt-transport-https
#sudo apt-get -y install collectd

cat <<EOF >interfaces
# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto enp0s3
iface enp0s3 inet static
 address 192.168.178.101
 netmask 255.255.255.0
 gateway 192.168.178.1
 dns-nameservers 8.8.8.8
EOF
sudo mv interfaces /etc/network

# Elastic
wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | sudo apt-key add -
echo "deb https://artifacts.elastic.co/packages/6.x/apt stable main" | sudo tee -a /etc/apt/sources.list.d/elastic-6.x.list
sudo apt-get update
sudo apt-get -y install elasticsearch
sudo /bin/systemctl daemon-reload
sudo /bin/systemctl enable elasticsearch.service

echo "cluster.name: kasteel-nijswiller" | sudo tee -a /etc/elasticsearch/elasticsearch.yml
echo "node.name: nijswiller-1" | sudo tee -a /etc/elasticsearch/elasticsearch.yml

# Logstash
sudo apt-get -y install logstash
sudo /bin/systemctl daemon-reload
sudo /bin/systemctl enable logstash.service

cat <<EOF > udp-9000.conf
input {
  udp { port => 9000 }
}
filter {
  grok {
    match => { "message" => "(?<application>.*?):(%{SPACE}(?<log-level>(DEBUG|INFO|WARN|ERROR|FATAL)):)?%{SPACE}(?<message>.*)" }
    overwrite => ["message"]
  }

  if [application] =~ "knx-event" {
    grok {
      match => { "message" => "receiver: (?<location>.*?) \((?<device-type>.*?)\) (?<device>.*?), (?<from-address>.*?)->(?<to-address>.*?) L_Data.ind, (?<l-data>.*?), tpdu (?<tpdu>.*?)$"}
      remove_field => [ "message" ]
    }
  }
}
output {
  elasticsearch {}
}
EOF
sudo mv udp-9000.conf /etc/logstash/conf.d/

#Kibana
sudo apt-get -y install kibana
sudo /bin/systemctl daemon-reload
sudo /bin/systemctl enable kibana.service
echo 'server.host: "0.0.0.0"' | sudo tee -a /etc/kibana/kibana.yml


# reboot and test
curl -XGET 'localhost:9200/?pretty'
curl localhost:5601/app/kibana
sudo /usr/share/logstash/bin/logstash -f /etc/logstash/conf.d/udp-9000.conf

exit 0