#!/bin/bash
#usage: guest-install name memsize poolname volume

sudo virt-install \
--name=$1 --ram=$2 --vcpus=3 \
--disk vol=$3/$4 \
--network bridge:br0 \
--nographics --os-type=linux --os-variant=ubuntu18.04 --virt-type=kvm \
--noapic --noacpi \
--location http://nl.archive.ubuntu.com/ubuntu/dists/bionic/main/installer-amd64/ \
--extra-args="serial console=ttyS0,57600"

exit 0
