#!/bin/bash
# Proxy server (apache)
sudo apt install qemu qemu-kvm libvirt-bin bridge-utils virt-manager 
sudo service libvirtd start 
sudo update-rc.d libvirtd enable 

echo Update network configuration to support bridge network:
echo network:
echo   version: 2
echo   ethernets:
echo     ens33:
echo       dhcp4: no
echo       dhcp6: no
echo
echo   bridges:
echo     br0:
echo       interfaces: [ens33]

sudo nano /etc/netplan/


cat <<EOF >>/tmp/br.xml 
<network>
  <name>br0</name>
  <forward mode='bridge'/>
  <bridge name='br0'/> 
</network> 
EOF 
sudo virsh net-define /tmp/br.xml 
sudo virsh net-start br0
sudo virsh net-autostart br0


