#!/bin/bash
# server for the iot-monitor server

# sudo apt install git
# and run git clone https://github.com/jstelwag/iot-monitor

sudo apt-get update
sudo apt-get -y upgrade
sudo apt-get -y install cron-apt curl openjdk-8-jdk maven redis-server git
#sudo apt-get -y install collectd

cat <<EOF >interfaces
# The loopback network interface
auto lo
iface lo inet loopback

# The primary network interface
auto enp0s3
iface enp0s3 inet static
 address 192.168.178.18
 netmask 255.255.255.0
 gateway 192.168.178.1
 dns-nameservers 8.8.8.8
EOF
sudo mv interfaces /etc/network

cat <<EOF >udp-listener.service
[Unit]
Description=Java UDP listener Service
[Service]
User=jaap
# The configuration file application.properties should be here:
#change this to your workspace
WorkingDirectory=/home/jaap
#path to executable. 
#executable is a bash script which calls jar file
ExecStart=/usr/local/bin/iot-runtime iot
SuccessExitStatus=143
TimeoutStopSec=10
Restart=on-failure
RestartSec=5
[Install]
WantedBy=multi-user.target
EOF

sudo mv udp-listener.service /etc/systemd/system/

sudo systemctl daemon-reload
sudo systemctl enable udp-listener.service
sudo systemctl start udp-listener
sudo systemctl status udp-listener

cat <<EOF >http-listener.service
[Unit]
Description=Java HTTP listener Service
[Service]
User=jaap
# The configuration file application.properties should be here:
#change this to your workspace
WorkingDirectory=/home/jaap
#path to executable. 
#executable is a bash script which calls jar file
ExecStart=/usr/local/bin/iot-runtime http
SuccessExitStatus=143
TimeoutStopSec=10
Restart=on-failure
RestartSec=5
[Install]
WantedBy=multi-user.target
EOF

sudo mv http-listener.service /etc/systemd/system/

sudo systemctl daemon-reload
sudo systemctl enable http-listener.service
sudo systemctl start http-listener
sudo systemctl status http-listener

cat <<EOF >monitor.conf
iot.port=8888
master.port=8000
influx.ip=192.168.178.18
influx.port=8087
logstash.ip=192.168.
logstash.port=9000
local.ip=192.168.
beds24.apiKey=
beds24.propKey=
EOF
sudo mv monitor.conf /etc

cat <<EOF >iot-upgrade
#!/bin/bash
/bin/bash /home/jaap/iot-monitor/src/main/bash/iot-upgrade
exit 0
EOF
sudo mv iot-upgrade /usr/local/bin
sudo chmod +x /usr/local/bin/iot-upgrade

cat <<EOF >iot-runtime
#!/bin/bash
sh /home/jaap/iot-monitor/src/main/bash/iot-runtime \$@
exit 0
EOF
sudo mv iot-runtime /usr/local/bin
sudo chmod +x /usr/local/bin/iot-runtime

git clone https://github.com/jstelwag/calimero.parent
cd calimero.parent
mvn install
cd ..

git clone https://github.com/jstelwag/calimero-core
cd calimero-core
mvn clean install -Dmaven.test.skip=true

git clone https://github.com/jstelwag/iot-monitor/
iot-upgrade

sudo nano /etc/monitor.conf

exit 0