#!/bin/bash
# raspberry pi setup script for iot-monitor
# first run git clone https://github.com/jstelwag/iot-monitor

sudo apt-get update
sudo apt-get -y install cron-apt rpi-update
sudo rpi-update
sudo apt-get -y install maven
#sudo apt-get -y install collectd

cat <<EOF >monitor.conf
iot.port=
master.port=
influx.ip=192.168.
influx.port=8087
knx.ip=192.168.
logstash.ip=192.168.
logstash.port=9000
local.ip=192.168.
beds24.apiKey=
beds24.propKey=
EOF
sudo mv monitor.conf /etc

cat <<EOF >iot-upgrade
#!/bin/bash
cd /home/pi/iot-monitor
git pull
sh src/main/bash/iot-upgrade
EOF
sudo mv iot-upgrade /usr/local/bin
sudo chmod +x /usr/local/bin/iot-upgrade

cat <<EOF >iot-runtime
#!/bin/bash
sh /home/pi/iot-solar-boiler/src/main/bash/iot-runtime $1
exit 0
EOF
sudo mv iot-runtime /usr/local/bin
sudo chmod +x /usr/local/bin/iot-runtime

iot-upgrade

sudo nano /etc/monitor.conf

exit 0